import mongoose, { Document, Schema, Types } from "mongoose";
import { SCHEDULE_DIRECTIONS, SCHEDULE_OPERATING_DAYS, SCHEDULE_TYPES, SCHEDULE_USER_TYPES } from "../../../constants";

export interface ISchedule {
  routeId: Types.ObjectId;
  direction: SCHEDULE_DIRECTIONS.TO_CAMPUS | SCHEDULE_DIRECTIONS.FROM_CAMPUS;
  time: string; // Time as string in "HH:mm" format
  userType: SCHEDULE_USER_TYPES.STUDENT | SCHEDULE_USER_TYPES.FACULTY | SCHEDULE_USER_TYPES.ADMIN;
  operatingDays: Array<
    | SCHEDULE_OPERATING_DAYS.SATURDAY
    | SCHEDULE_OPERATING_DAYS.SUNDAY
    | SCHEDULE_OPERATING_DAYS.MONDAY
    | SCHEDULE_OPERATING_DAYS.TUESDAY
    | SCHEDULE_OPERATING_DAYS.WEDNESDAY
    | SCHEDULE_OPERATING_DAYS.THURSDAY
    | SCHEDULE_OPERATING_DAYS.FRIDAY
  >;
  type: SCHEDULE_TYPES.REGULAR | SCHEDULE_TYPES.MID_TERM | SCHEDULE_TYPES.FINAL_TERM;
  notes: string;
}

